email:
  reg:
    from: "support@mineleague.ru"
    subject: "Регистрация на MineLeague.ru"
    htmlBody: "<p>Добро пожаловать на проект MineLeague!</p>

      <p>Для того чтобы подтвердить регистрацию, перейдите по ссылке:</p>
      
      <p>https://mineleague.ru/auth/reg/confirm/%token%</p>
      
      <p>С уважением, команда MineLeague!</p>
      
      <p>Связаться с нами:</p>
      <p>Тех. поддержка - support.mineleague.ru</p>
      <p>Группа ВК - vk.com/mineleague</p>
      <p>Сайт - mineleague.ru</p>"
    charSet: "UTF-8"
  passReset:
    from: "support@mineleague.ru"
    subject: "Восстановление пароля MineLeague.ru"
    htmlBody: "<p>На Ваш аккаунт %username% было запрошено восстановление пароля с IP адреса %ip_address%.</p>
  
      <p>Если это отправили не Вы, просто проигнорируйте это сообщение.</p>
      
      <p>Для того чтобы восстановить пароль, перейдите по ссылке - %pass_reset_link%</p>
      
      <p>С уважением, команда MineLeague!</p>
      
      <p>Связаться с нами:</p>
      <p>Тех. поддержка - support.mineleague.ru</p>
      <p>Группа ВК - vk.com/mineleague</p>
      <p>Сайт - mineleague.ru</p>"
    charSet: "UTF-8"